# spring-boot-docker/docker-compose.yml
#version: "3.7"
docker-compose version 1.25.4, build unknown
docker-py version: 4.2.0
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019

services:
  mysql-service:
    image: mysql:5.7
    networks:
      - bookstore-mysql-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=espoir
      - MYSQL_DATABASE=bookstore
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - bookstore-mysql-network
    depends_on:
      - mysql-service
networks:
  bookstore-mysql-network:
    driver: bridge